task-completed
MaKu-kodilla/node.js-practice pull request #1
Opened 2018-04-22 13:24 UTC by MaKu-kodilla

2018-04-23 13:41 UTC, michal-bootcamp requested changes
Oczekuje czegos takiego:
Jak uruchomie program przez `node program.js` wyswietli mi sie info jakie komendy mam do wyboru i jak bede wpisywal nastepujace komendy, to powinienem dostawac odpowiedni wynik np:
- /info - wyswietli informacje o wersji node
- /lang - wyswietli informacje o jezyku srodowiska
- /exit - poinformuje o wyjsciu z programu i zakonczy dzialanie skryptu
- bledna komenda - wyswietli error "Wrong instruction!"

2018-04-23 13:41 UTC, michal-bootcamp commented on Zadanie 13.1 Badamy środowisko/program.js
> +        switch (instruction === '/exit') {
sprawdz jak dziala switch: https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Polecenia/switch

2018-04-23 13:41 UTC, michal-bootcamp commented on Zadanie 13.1 Badamy środowisko/program.js
> +console.log(process.env);
console.log niepotrzebny

2018-04-23 15:35 UTC, MaKu-kodilla commented
Teraz powinno być ok :)

2018-04-23 21:21 UTC, michal-bootcamp requested changes
1. wyrownaj prosze wciecia wewnatrz switcha, przejrzysciej bedzie w ten sposob: https://scr.hu/nRK6oM
2. przenies komende /exit zeby byla ostatnia przed defaultem - logiczniej sie to wtedy czyta

2018-04-23 21:21 UTC, michal-bootcamp commented on Zadanie 13.1 Badamy środowisko/program.js
> +            console.log(process.env);
tutaj wyswietla sie masa informacji - wyluskaj z nich i wyswietl tylko jezyk

2018-04-26 20:56 UTC, michal-bootcamp requested changes

2018-04-26 20:56 UTC, michal-bootcamp commented on Zadanie 13.1 Badamy środowisko/program.js
> +                console.log(process.env.lang);
u mnie `Language: undefined`
podpowiem, ze wielkosc liter ma tutaj znaczenie :)

2018-04-30 17:16 UTC, MaKu-kodilla commented on Zadanie 13.1 Badamy środowisko/program.js
> +                console.log(process.env.lang);
https://scr.hu/OzABkl

zmieniłem na same wielkie litery, ale przy małych też u mnie działo!

2018-05-02 10:03 UTC, michal-bootcamp commented on Zadanie 13.1 Badamy środowisko/program.js
> +                console.log(process.env.lang);
teraz git, no prosze, a u mnie dopiero z wielkich liter dziala :)

2018-05-02 10:03 UTC, merged